.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH path_master 1  "path_master " 
.SH NAME
path_master
.SH SYNOPSIS
\fBpath_master\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-c\fR|\fB\-\-count\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<NAME>\fR

.TP
\fB\-c\fR, \fB\-\-count\fR \fI<NUM>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
